name: Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create mock submodule content
      run: |
        mkdir -p personal jungehaie
        echo "# Personal dotfiles loaded" > personal/zshrc
        echo "# Jungehaie dotfiles loaded" > jungehaie/zshrc

    - name: Install dotfiles
      run: ./install
